name: Deploy workflow

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

jobs:
  copy_compose:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

#      - name: Copy file
#        uses: garygrossgarten/github-action-scp@release
#        with:
#          host: ${{ secrets.server_host }}
#          username: ${{ secrets.server_username }}
#          password: ${{ secrets.server_password }}
#          port: ${{ secrets.server_port }}
#          local: ${{ inputs.source }}
#          remote: ${{ inputs.target }}

      - name: Restart containers
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          command: |
            cd docker
            sudo docker compose -f docker-compose-server.yaml up -d