name: Deploy workflow

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: false
    secrets:
      SERVER_HOST:
        required: true
      SERVER_USERNAME:
        required: true
      SERVER_PASSWORD:
        required: true
      SERVER_PORT:
        required: true

jobs:
  copy_compose:
  #  environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

#      - name: Copy file
#        uses: garygrossgarten/github-action-scp@release
#        with:
#          host: ${{ secrets.server_host }}
#          username: ${{ secrets.server_username }}
#          password: ${{ secrets.server_password }}
#          port: ${{ secrets.server_port }}
#          local: ${{ inputs.source }}
#          remote: ${{ inputs.target }}


      - name: Dump Host
        run: |
          echo Password is $HOST
          if [[ $HOST = *"digital.merphi.ru"* ]]; then
            echo "This is the correct host!"
          else
            echo "This is NOT the correct host!"
          fi
        env:
          HOST: ${{ secrets.SERVER_HOST }}

      - name: Restart containers
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: digital.merphi.ru
          username: ubuntu
          password: RO{HE@yH7H~fPE~e
          port: 2233
          script: ls
            #sudo docker compose -f docker-compose-server.yaml up -d