name: Deploy workflow

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

jobs:
  copy_compose:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

#      - name: Copy file
#        uses: garygrossgarten/github-action-scp@release
#        with:
#          host: ${{ secrets.server_host }}
#          username: ${{ secrets.server_username }}
#          password: ${{ secrets.server_password }}
#          port: ${{ secrets.server_port }}
#          local: ${{ inputs.source }}
#          remote: ${{ inputs.target }}

      - name: Connect to the server
        run: ssh -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USERNAME }}@${{secrets.SERVER_HOST }}

      - name: Enter password
        run: ${{ secrets.SERVER_PASSWORD }}

      - name: cd Docker
        run: cd Docker
