name: CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/**'
      - 'docker/docker-compose-server.yaml'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'backend/**'
      - '.github/workflows/**'

jobs:
  deploy-prod:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
      scp_local: 'docker/docker-compose-server.yaml'
      scp_remote: '/home/ubuntu/docker-compose-server.yaml'
    secrets: inherit

#


