name: CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'backend/**'
      - '.github/workflows/**'


env:
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'corretto'
  CACHE_BUILD_TOOL: 'maven'
  CACHE_PATH: 'backend/pom.xml'
  TEST_REPORT_PATH: '**/target/surefire-reports/TEST-*.xml'

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      java_version: ${{ env.JAVA_VERSION }}
      java_distribution: ${{ env.JAVA_DISTRIBUTION }}
      cache_build_tool: ${{ env.CACHE_BUILD_TOOL }}
      cache_path: ${{ env.CACHE_PATH }}
      test_report_path: ${{ env.TEST_REPORT_PATH }}

  build:
    if: github.event-name != 'pull_request'
    needs: test
    uses: ./.github/workflows/build.yml
    secrets: inherit
