name: CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/**'
      - 'docker/docker-compose-server.yaml'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'backend/**'
      - '.github/workflows/**'

jobs:
  deploy-prod:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
    secrets:
      source: 'docker/docker-compose-server.yaml'
      target: '/home/ubuntu/'
      # в таргет добавить docker-compose-server.yaml
      server_host: ${{ secrets.SERVER_HOST }}
      server_username: ${{ secrets.PROD_SERVER_USERNAME }}
      server_password: ${{ secrets.PROD_SERVER_PASSWORD }}
      server_port: ${{ secrets.PROD_SERVER_PORT }}