name: CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'backend/**'
      - '.github/workflows/**'

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      scp_source: 'docker/docker-compose-server.yaml'
      scp_target: '/home/ubuntu/'
      overwrite: true
    secrets:
      server_host: ${{ secrets.SERVER_HOST }}
      server_username: ${{ secrets.SERVER_USERNAME }}
      server_password: ${{ secrets.SERVER_PASSWORD }}
      server_port: ${{ secrets.SERVER_PORT }}
